version: '3'

services:
    spectra-parser-service:
        restart: always
        container_name: spectra-file-parser
        image: docker.your-company.com/sds/spectra-file-parser:latest
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        volumes:
        - /home/logs:/logs/
        - /home/temp:/temp/
        build:
            context: .
        ports:
        - 8985:8085
        networks:
        - osdr-net-ext
            
networks:
    osdr-net-ext:
        external:
            name: osdr-sys-net
